# experimental tests with new HumHub docker image
services:
  humhub:
    image: humhub/humhub:stable-nightly # need to change to a release after testing.
    restart: unless-stopped
    ports:
      - "80:80"
      # - "443:443"
      # - "443:443/udp"  # HTTP/3 (optional)
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./humhub-data:/data
    env_file:
      - ./humhub.env
    environment:
      - HUMHUB_DEBUG=true
      - SERVER_NAME=":80" #force it to not use Caddy's TLS termination?
      - HUMHUB_CONFIG__COMPONENTS__DB__DSN=mysql:host=db;dbname=humhub
      - HUMHUB_CONFIG__COMPONENTS__DB__USERNAME=${HUMHUB_DOCKER_DB_USER}
      - HUMHUB_CONFIG__COMPONENTS__DB__PASSWORD=${HUMHUB_DOCKER_DB_PASSWORD}
  db:
    image: mariadb
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    user: root
    # for offen BU, tell mariadb-dump to add a drop database and drop table statement so that 
    #  the restore will use a clean database
    # note the hard-coded database name humhub (FIXME?)
    labels:
      - "docker-volume-backup.archive-pre=/bin/sh -c 'mariadb-dump \
        --databases humhub \
        --add-drop-database \
        --add-drop-table \
        --default-character-set=utf8mb4 \
        -u${HUMHUB_DOCKER_DB_USER} \
        -p${HUMHUB_DOCKER_DB_PASSWORD} \
        > /tmp/dumps/dump.sql'"

    volumes:
      - ./mysql-data:/var/lib/mysql
      - db-dump:/tmp/dumps
    environment:
      - MYSQL_ROOT_PASSWORD=${HUMHUB_DOCKER_DB_PASSWORD}
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  # dpm add offen/docker-volume-backup sidecar for testing
  # must use version v2 to support mariadb-dump
  backup:
    image: offen/docker-volume-backup:v2
    restart: unless-stopped
    env_file:
      - ./backup.env
    volumes:
      # bind-mount the HumHub data dir read-only into /backup/humhub-data
      # this saves only the /data/uploads dir 
      - ./humhub-data/uploads:/backup/humhub-data/uploads:ro
      # volume mount the MySQL temp dump read-only into /backup/db-dump
      - db-dump:/backup/db-dump:ro
      
      # make a local copy for testing (into ./backups-local) 
      - ./backups-local:/archive
      # - ./caddy-data:/data/caddy-data
      # allow the backup container to stop & start the HumHub container
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #
      # added to allow weekly and monthly backups using backup-conf.d
      #off_for_testing - ./backup-conf.d:/etc/dockervolumebackup/conf.d:ro

    # optional: label humhub so it’s stopped during backup for consistency
    # labels:
    #   - docker-volume-backup.stop-during-backup=true

    # environment:
    #   # every day at 2am (use UTC = DST+5)
    #   BACKUP_CRON_EXPRESSION: 0 7 * * *
    #   BACKUP_FILENAME: backup-humhubdata-%Y-%m-%dT%H-%M-%S.tar.gz
    #   BACKUP_PRUNING_PREFIX: backup-
    #   BACKUP_RETENTION_DAYS: 30
volumes:
  db-dump: